### ISSUE TITLE
Avatar support

### ISSUE THREAD

**Issue by devmsh** [64robots/nova-image-cropper#1]
Thanks for the library

Did you plan to support avatar?

**Comment by disitec** [comment]
You can achieve this using an Avatar field for the other views: 

```php
ImageCropper::make('Photo')->disk('s3')->onlyOnForms(),
Avatar::make('Photo')->disk('s3')->exceptOnForms(),
```

This way you see an avatar in detail and index view and you can edit the image in forms

**Comment by devmsh** [comment]
Why I need to do this nested of having Single Field?

**Comment by disitec** [comment]
1.0.4 published. Theres no need to use Avatar field when using

```php
ImageCropper::make('Photo')->avatar(),
```

**Comment by dddeeemmmooonnn** [comment]
I created new empty custom field that extends ImageCropper and implements Cover:
```
use Laravel\Nova\Contracts\Cover;
use R64\NovaImageCropper\ImageCropper as R64ImageCropper;

class NovaImageCropper extends R64ImageCropper implements Cover
{

}
```
avatars are displayed in search
