### ISSUE TITLE
Image preview goes out of box

### ISSUE THREAD

**Issue by FaridAghili** [64robots/nova-image-cropper#11]
The transparent like box, around the image preview goes out of the box while cropping.

Check this out:
![2nu33a](https://user-images.githubusercontent.com/8607021/49299239-7fd96d80-f4d4-11e8-82ee-bdb582e6c469.gif)

**Comment by FaridAghili** [comment]
Google chrome 70.0.3538.110
720x1280

**Comment by disitec** [comment]
This has been fixed on `1.1.0` 🎉
