### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by FaridAghili** [64robots/nova-image-cropper#12]
I'm getting this error randomly on index, details and edit page for records with an image. I guess it's related to the image preview, because when there is no image on any records, everything works as expected, but right after adding an image to first record, this error happens.

My resource is as simple as:

```php
            ImageCropper::make('Image')
                ->prunable()
                ->rules('nullable', 'image', 'max:5120')
                ->aspectRatio(10 / 8)
```

**Comment by disitec** [comment]
By default the fields try to generate a preview. This is the code:

https://github.com/64robots/nova-image-cropper/blob/master/src/ImageCropper.php#L30

You can redefine this function as long you return a base64 encoded image.

```php
ImageCropper::make('Image')
                ->prunable()
                ->rules('nullable', 'image', 'max:5120')
                ->aspectRatio(10 / 8)
                ->preview(function () {
                       return $your_base64_image;
                })

```

Let me know if we can improve the default implementation in some way.
