### ISSUE TITLE
Buttons wrap on smaller screens

### ISSUE THREAD

**Issue by mattstauffer** [64robots/nova-image-cropper#15]
Y'all, I am so happy for this package. Thank you!

Quick note: The button text wraps on smaller screens, and it'd be awesome if it didn't. <3

![image](https://user-images.githubusercontent.com/151829/52759789-35e42c00-2fdb-11e9-99d9-554ee5d4aed4.png)

**Comment by robmpreston** [comment]
Thanks Matt! We'll get that fixed soon. 👍

**Comment by disitec** [comment]
This has been fixed in 1.1.3 🎉 😸

**Comment by mattstauffer** [comment]
Woo woo!!!
