### ISSUE TITLE
Image always stored in PNG format

### ISSUE THREAD

**Issue by akmalelias** [64robots/nova-image-cropper#18]
Version: 1.1.4

Image always stored in PNG format. How to store image follow original type?

And how to store original filename in the storage path? Currently if using storeOriginalName() method, it only save the original name in that particular database column, not as the actual file name in the storage path.

**Comment by disitec** [comment]
Fixed in 1.1.5.

You can read in the File Field documentation how to customize the storage

https://nova.laravel.com/docs/2.0/resources/file-fields.html#customization
