### ISSUE TITLE
Circle cropping

### ISSUE THREAD

**Issue by devmsh** [64robots/nova-image-cropper#2]
Is there anyway to customize the cropper and use Circular cropper placeholder? so we can see if the image will displayed probably in circle in the app?

**Comment by disitec** [comment]
This is not intended to implement but maybe could be a good idea enable/disable an avatar mask so you can see how this is gonna end up inside an Avatar field.

**Comment by disitec** [comment]
You can now add a rounded mask to the preview and the cropper

```php
ImageCropper::make('Photo')->avatar()
```

Just published 1.0.3

**Comment by mustafaaloko** [comment]
Hi, just curious, why not use the default `rounded` attribute which is already available in the `Image` field class?
