### ISSUE TITLE
Don't removes old image when upload a new one

### ISSUE THREAD

**Issue by wemersonrv** [64robots/nova-image-cropper#20]
When edit & save a new resource, and upload/crops an image, the new uploaded image is stored fine. But the old image is not removed on store.

If user change the image, i don't understand the need to mantain the old image; so i thing the old image must be removed.

**Comment by disitec** [comment]
This field extends nova File field. So this methods are available for you.

https://nova.laravel.com/docs/2.0/resources/file-fields.html#pruning-deletion

**Comment by wemersonrv** [comment]
> This field extends nova File field. So this methods are available for you.
> 
> https://nova.laravel.com/docs/2.0/resources/file-fields.html#pruning-deletion

It works with `->prunable()` 

tx
