### ISSUE TITLE
Strange issue with website with basic auth

### ISSUE THREAD

**Issue by alberto-bottarini** [64robots/nova-image-cropper#8]
Hi, I cannot get image preview on my production environment (where a basic auth is available).

Looking into your code I found this snippet

            $url = Storage::disk($this->disk)->url($this->value);

            $path_info = pathinfo($url);

            $filetype = 'jpg';

            if (array_key_exists('extension', $path_info)) {
                $filetype = $path_info['extension'];
            }

            try {
                $encoded_file = base64_encode(file_get_contents($url));
            } catch (\Exception $e) {
                return '';
            }

This force PHP to perform a http request because ->url method, on Storage, return an absolute url (that breaks down on my environment).

I don't know if it's the right behaviour....

**Comment by disitec** [comment]
You can override the preview method in your resource and apply the logic that you could need as long as you return a base64 encoded image.

https://github.com/64robots/nova-image-cropper#update-form

**Comment by disitec** [comment]
You can override the preview method in your resource and apply the logic that you could need as long as you return a base64 encoded image.

https://github.com/64robots/nova-image-cropper#update-form

**Comment by alberto-bottarini** [comment]
Don't you think that this is a strange behavior? 
This HTTP request is not needed, you can base64 encode using a "local" path....

You should do a file_get_contents("image.jpg").

**Comment by robmpreston** [comment]
@alberto-bottarini That's just an example, if that works for you then do it that way. 

For us, we use S3 for image storage on almost every project so we can't use a local path.
