### ISSUE TITLE
Aspect ratio should be "forced"

### ISSUE THREAD

**Issue by alberto-bottarini** [64robots/nova-image-cropper#9]
If I define an aspect ratio, editor should open automatically "edit image" after upload in order to force user to crop the image.

If users ignore this step, they could upload not cropped image.

**Comment by alberto-bottarini** [comment]
Thanks, but now it open "edit image" always, not just after image upload :'(

**Comment by disitec** [comment]
fixed in 1.0.8

**Comment by alberto-bottarini** [comment]
It seems ok. Thanks a lot
